### ISSUE TITLE
Import All not working

### ISSUE THREAD

**Issue by Stanzilla** [Juulsn/todo-issue#2]
Hey there! My config looks like this

```yml
name: Create issues for TODOs

on:
  workflow_dispatch:
    inputs:
      importAll:
        default: "false"
        required: false
        type: boolean
        description: Enable, if you want to import all TODOs.
  push:
    branches:
      - development

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  todos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Issue Bot
        uses: derjuulsn/todo-issue@main
        with:
          excludePattern: "^(mkdocs-material/|src/assets/javascripts/)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

Yet, every time I want to kick off a manual run with import all, it errors with `Action can only be used on trigger push or in manual and importAll mode` any ideas?

**Comment by Juulsn** [comment]
Hey! Did you activate the Import All option before you click `Run Workflow`?

![image](https://user-images.githubusercontent.com/25909319/150804861-89ae6642-385e-412c-b710-2609dfa151ba.png)

**Comment by Stanzilla** [comment]
> Hey! Did you activate the Import All option before you click `Run Workflow`?
> 
> ![image](https://user-images.githubusercontent.com/25909319/150804861-89ae6642-385e-412c-b710-2609dfa151ba.png)

Yeah I did! Could it be something about the quotes? Your example has single quotes, I use double?

**Comment by Juulsn** [comment]
Nope, that shouldn't be it. As a workaround: change the input type to string instead of boolean and write true in the text field.
That should work.
I've read something about bools are not real bools in workflow inputs but kinda ignored it haha :)

**Comment by Stanzilla** [comment]
> Nope, that shouldn't be it. As a workaround: change the input type to string instead of boolean and write true in the text field. That should work. I've read something about bools are not real bools in workflow inputs but kinda ignored it haha :)

Still fails, sadly :(

The logs don't have much either:

```
2022-01-24T15:30:49.5493690Z [command]/usr/bin/git log -1 --format='%H'
2022-01-24T15:30:49.5525703Z '899b4abbafd91466ab0696644f33e98c3714d509'
2022-01-24T15:30:49.5778210Z ##[group]Run derjuulsn/todo-issue@main
2022-01-24T15:30:49.5778502Z with:
2022-01-24T15:30:49.5778809Z   excludePattern: ^(mkdocs-material/|src/assets/javascripts/)
2022-01-24T15:30:49.5779124Z   keywords: TODO
2022-01-24T15:30:49.5779490Z env:
2022-01-24T15:30:49.5780106Z   GITHUB_TOKEN: ***
2022-01-24T15:30:49.5780328Z ##[endgroup]
2022-01-24T15:30:51.6131335Z ##[error]Action can only be used on trigger push or in manual and importAll mode
2022-01-24T15:30:51.6819161Z Post job cleanup.
```

**Comment by Juulsn** [comment]
You can change your input type back to boolean now. The latest change should fix the issue.

**Comment by Stanzilla** [comment]
Edit: looks like it worked, thanks!

**Comment by gunar** [comment]
I'm having the same problem:

>  Action can only be used on trigger push or in manual and importAll mode

Tried all variations of `default: 'true'`, `type: boolean` and `type: string`, etc… nothing makes `importAll` work :(

I'm wondering if this exceptions that is thrown has anything to do with it:

![image](https://user-images.githubusercontent.com/7684574/183265821-5fb0cec5-72c0-4bfa-8a31-2abb7a4306ac.png)

**Comment by Juulsn** [comment]
Hey @gunar

solved it with v1.1.3. Sorry for responding that late. 
Overlooked the comment in this closed issue ;)

**Comment by gunar** [comment]
@DerJuulsn Thanks for circling back. I'm still getting `Error: Action can only be used on trigger push or in manual and importAll mode`.

I'm assuming `@main` should get me the latest version right?

![image](https://user-images.githubusercontent.com/7684574/188500433-ac4d4cdb-5a6d-43f9-8672-63d725731fae.png)

**Comment by Juulsn** [comment]
@gunar My bad, fixed now!

**Comment by gunar** [comment]
Much better, thanks @DerJuulsn!
